### ISSUE TITLE
fails to build with recent swift toolchains

### ISSUE THREAD

**Issue by JaapWijnen** [tayloraswift/swift-png#73]
swift-png fails to build with recent toolchains due to parts of tuples being used before the full value has been initialised. 
`Constant 'next.upstream' used before being initialized`

reproducible with main nightly: 2024-07-22

**Comment by tayloraswift** [comment]
i wasn’t able to reproduce it with the 6.0 beta (`swift-6.0-DEVELOPMENT-SNAPSHOT-2024-07-16-a`), so this is likely a type-checking regression in the nightly Swift compiler. type-checking regressions are very (!) common on the nightlies, and unfortunately it is not realistic to patch libraries for every compiler bug, so i ask that you please file this on [swiftlang/swift](https://github.com/swiftlang/swift/issues) so that a compiler dev can fix the root cause.
